// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcISW8QuQsrsEWWYcBZOEa_eWoTfJXIds',
    appId: '1:652067924410:web:ff7372f677c65d3c6e5583',
    messagingSenderId: '652067924410',
    projectId: 'beta-d6beb',
    authDomain: 'beta-d6beb.firebaseapp.com',
    storageBucket: 'beta-d6beb.appspot.com',
    measurementId: 'G-VK1VVW7DFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CBf3UXzL6DFwQKVty5T2I6Rfxd0__o4',
    appId: '1:652067924410:android:47aa58d6c6e6574b6e5583',
    messagingSenderId: '652067924410',
    projectId: 'beta-d6beb',
    storageBucket: 'beta-d6beb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJv49s0fo1YHBCO6iISf3b2nusynQDh2Y',
    appId: '1:652067924410:ios:8abb0069c9de9fb56e5583',
    messagingSenderId: '652067924410',
    projectId: 'beta-d6beb',
    storageBucket: 'beta-d6beb.appspot.com',
    iosClientId: '652067924410-g4n5g68b691obkaqt16cervc6949n51j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJv49s0fo1YHBCO6iISf3b2nusynQDh2Y',
    appId: '1:652067924410:ios:8abb0069c9de9fb56e5583',
    messagingSenderId: '652067924410',
    projectId: 'beta-d6beb',
    storageBucket: 'beta-d6beb.appspot.com',
    iosClientId: '652067924410-g4n5g68b691obkaqt16cervc6949n51j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBase',
  );
}
